### ISSUE TITLE
Error message should be thrown when an invalid passphrase is entered by user

### ISSUE THREAD

**Issue by kashifali007** [SuperNETorg/Iguana-application#20]
Error message should be thrown when an invalid passphrase is entered by user

Steps to reproduce:
1. Make sure you have latest code
2. gulp prod
3. open latest index.html in browser
4. start coind
5. create passphrase through coind cli
6. enter invalid passphrase through iguana gui
7. Click on login button

you will be observing here that no error message is thrown.

Expected result:

I guess an error message should be thrown indicating that passphrase isn't valid

**Comment by arkadig** [comment]
@kashifali007 I can't reproduce the issue you mentioned. I see those are already fixed.
please check again.

**Comment by pbca26** [comment]
@arkadig the issue still persist. Have a look, I have a bunch of errors in console and no error message at all.

![no-error-on-wrong-passphrase](https://cloud.githubusercontent.com/assets/7769879/21719531/6bb43bea-d42f-11e6-930a-015745690409.png)

**Comment by arkadig** [comment]
@kashifali007 I am done with this. Can you please check it?

**Comment by kashifali007** [comment]
Hi @arkadig 

Issue seems fix now but doesn't throw a meaning information. so I think we should fix this also. 
![wrongpassphrase](https://cloud.githubusercontent.com/assets/16662663/21767478/463d0e82-d696-11e6-93bf-a476eb9926d2.png)

**Comment by kashifali007** [comment]
error message issue has been fixed however I'm observing another issue. i will log it separately @arkadig 

cc: @pbca26 @imboogieman
